### ISSUE TITLE
Deploy RabbitMQ

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-graph-node#29]
- determine which  Rabbit chart to deploy with (likely Bitnami) 
- investigate to determine the best production for deploy

**Comment by andricDu** [comment]
## Summary
So my investigation has landed on using the RabbitMQ operator for Kubernetes provided by the RabbitMQ project: https://www.rabbitmq.com/kubernetes/operator/operator-overview.html

This adds a new RabbitMqCluster resource type to kubernetes.

## Technical Hurdles Solved
The operator did not work out of the box for the following reasons:
- Network Policies needed to be set up
- PodSecurityPolicies stopped the init container from setting up the cluster

## Poc Solution
The following is how to install the operator and then deploy a cluster getting around the technical problems described above:

### Installation of Operator
```shell
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
```

### Deployment of Cluster with 1 replica
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: rabbitmq-dev
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
      - "CHOWN"
      - "FOWNER"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
  - persistentVolumeClaim
  - emptyDir
  - downwardAPI
  - projected
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq
rules:
- apiGroups:
  - policy
  resourceNames:
  - rabbitmq-dev
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq
subjects:
- kind: ServiceAccount
  name: wfg-rabbit-rabbitmq-server
  namespace: rdpc-collab-dev
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbit
  namespace: rdpc-collab-dev
spec:
  egress:
  - ports:
    - port: 6443
      protocol: TCP
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.10.0.0/16
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: rabbitmq
  podSelector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: wfg-rabbit
spec:
  replicas: 1
  override:
    statefulSet:
      metadata:
        labels:
          rabbitmq: workflow-graph

```

## Next Steps
Obviously the provided yaml above is huge and shouldn't be the concern every time someone tries to deploy a new rabbit cluster for testing or otherwise. 
1. Author Helm Chart for RabbitMQ Operator usage https://github.com/icgc-argo/workflow-roadmap/issues/50
2. Deploy RabbitMQ for the various namespaces
